spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_Tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
# spring.jpa.hibernate.ddl-auto=create
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
spring.jpa.generate-ddl=true
